const patients = [
  {
    id: 1,
    name: "Ankita Sharma",
    newreport: "Yes",
    purpose: "Cough and runny nose since 5 days ago",
    profile: "/images/ankita.jpg",
    age: 21,
    gender: "Male",
    weight: "52kg",
    height: "5'6ft",
    maritialstatus: "Unmarried",
  },
  {
    id: 2,
    name: "Prashant Srivastava",
    newreport: "No",
    purpose: "Cough and runny nose since 5 days ago",
    profile: "/images/prashant.jpg",
    age: 21,
    gender: "Male",
    weight: "60kg",
    height: "5'6ft",
    maritialstatus: "Unmarried",
  },
  {
    id: 3,
    name: "Suraj Paliwal",
    newreport: "Yes",
    purpose: "Cough and runny nose since 5 days ago",
    profile: "/images/suraj.jpg",
    age: 21,
    gender: "Male",
    weight: "65kg",
    height: "5'6ft",
    maritialstatus: "Married",
  },
];

export default patients;
